### ISSUE TITLE
Can use it for Code-review?

### ISSUE THREAD

**Issue by kuien** [tht13/gerrit-vscode#6]
I can neither find the place to setup gerrit server, nor add comments on editor. Do I miss something?

**Comment by tht13** [comment]
Sorry this extension does not yet have code-review tools. At the moment it is not a feature I am planning on adding, unless there is large support for it.
The main purpose of this extension is to provide UI actions to perform traditional gerrit cmd commands, for example `git push origin HEAD:refs/for/master`
